# Generated by Django 5.2.14 on 2026-05-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_model',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фотоаппарат'),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_format',
            field=models.CharField(blank=True, default='JPG', max_length=20, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='photo',
            name='license_type',
            field=models.CharField(choices=[('free', 'Бесплатно для любых целей'), ('restricted', 'Права ограничены автором')], default='free', max_length=20, verbose_name='Права использования'),
        ),
        migrations.AddField(
            model_name='photo',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, verbose_name='Разрешение'),
        ),
        migrations.AddField(
            model_name='photo',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название фото'),
        ),
    ]
