# Generated by Django 4.2.30 on 2026-06-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='photo',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/watermarked/', verbose_name='Фото с водяным знаком'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Оригинальное фото'),
        ),
    ]
